export type HabitPlan = {
  minimum: string
  cue: string
  environment: string
  reward: string
  ifThen: string
  rationale: string
  focus: string
  recommendations: string[]
}

const first = (value: string, fallback: string) => value.trim() || fallback

/** A transparent, evidence-linked planner. It deliberately recommends only techniques
 * represented in the Habit Lab (if–then plans, stable context, environmental friction,
 * small actions, feedback) instead of making clinical or unsupported claims. */
export function buildSciencePlan(name: string, kind: 'build'|'break', cue: string, replacement = ''): HabitPlan {
  const n = name.toLowerCase()
  const anchor = first(cue.replace(/^after i\s*/i,''), kind === 'build' ? 'finish an existing daily routine' : 'notice the urge')
  if (kind === 'break') {
    const screen=/scroll|phone|social|instagram|tiktok/.test(n),snack=/junk|snack|sugar|food|eat/.test(n),spend=/spend|shopping|buy|money/.test(n),substitute=first(replacement,screen?'stand up and take a two-minute screen-free break':snack?'drink water and wait two minutes before deciding':spend?'add it to a 24-hour list before buying':'pause for two slow breaths and choose a brief alternative')
    const environment=screen?'Move the app off your home screen, sign out, and keep the phone out of reach during focus time.':snack?'Put a satisfying alternative at eye level and move the trigger food out of sight.':spend?'Remove saved payment details and keep a 24-hour waiting list visible.':'Put one extra step between the trigger and the behaviour.'
    return { minimum:'Pause before the behaviour for two minutes', cue:`When I ${anchor}`, environment, reward:'Mark the pause, not perfection.', ifThen:`When I ${anchor}, I will ${substitute} before deciding.`, rationale:'A specific response plan and a little more friction can make the automatic option easier to notice and interrupt.', focus:screen?'Reduce instant screen access':snack?'Change the easiest food choice':spend?'Create a waiting step before buying':'Interrupt the automatic response', recommendations:[environment,`Use this replacement: ${substitute}.`,'Track the pause as a win, even if you later choose the old behaviour.'] }
  }
  if (/read|book/.test(n)) return {minimum:'Open the book and read two pages',cue:`After I ${anchor}`,environment:'Put the book exactly where the cue happens.',reward:'Tick the check-in after the two pages.',ifThen:`After I ${anchor}, I will open my book and read two pages.`,rationale:'A stable cue and a deliberately small start reduce the effort required at the moment of action.',focus:'Make reading the obvious next step',recommendations:['Leave the book open or visible at the exact cue location.','Choose the next page before you stop today.','Protect a two-page minimum; anything extra is optional.']}
  if (/study|learn|work|write|assignment|coding|code/.test(n)) return {minimum:'Open the task and work for five minutes',cue:`After I ${anchor}`,environment:'Leave the document open and silence or move your phone.',reward:'A short guilt-free break after the timer.',ifThen:`After I ${anchor}, I will open the task and work for five minutes.`,rationale:'Turning a vague goal into a visible first action makes starting easier to repeat.',focus:'Lower the cost of starting focused work',recommendations:['Prepare the document, book, or tab before the cue happens.','Put the phone out of reach for the first five minutes.','Define success as opening the task—not finishing it.']}
  if (/walk|run|exercise|workout|gym|move/.test(n)) return {minimum:'Put on your shoes and move for two minutes',cue:`After I ${anchor}`,environment:'Place your shoes or workout clothes in sight beforehand.',reward:'Choose a pleasant podcast or music only for this routine.',ifThen:`After I ${anchor}, I will put on my shoes and move for two minutes.`,rationale:'Preparing the environment and counting the smallest version removes several decisions before movement starts.',focus:'Make showing up the whole goal',recommendations:['Prepare shoes or clothes before the day begins.','Use only your chosen practice days—rest days do not break the plan.','Pair movement with music or a podcast you genuinely enjoy.']}
  if (/water|drink/.test(n)) return {minimum:'Take three sips',cue:`After I ${anchor}`,environment:'Keep a filled bottle where the cue occurs.',reward:'Watch the daily progress rise immediately.',ifThen:`After I ${anchor}, I will take three sips of water.`,rationale:'Visibility and convenience are more reliable supports than trying to remember a broad daily target.',focus:'Make water the easiest visible choice',recommendations:['Fill the bottle before the cue, not after it.','Keep it within arm’s reach where you work or eat.','Tie three sips to a routine you already do.']}
  if (/sleep|bed|wind.?down/.test(n)) return {minimum:'Complete a two-minute wind-down action',cue:`After I ${anchor}`,environment:'Set the charger away from the bed and dim the room.',reward:'Use a calming activity you genuinely enjoy.',ifThen:`After I ${anchor}, I will plug in my phone and start my two-minute wind-down.`,rationale:'A consistent transition cue can help make the desired first step easier to notice and start.',focus:'Build a simple transition into sleep',recommendations:['Set a reminder for the beginning of the wind-down, not just bedtime.','Charge the phone away from the bed.','Choose one calming two-minute action to repeat.']}
  if (/pray|prayer|meditat|mindful|breath/.test(n)) return {minimum:'Stand or sit in the chosen place for two minutes',cue:`After I ${anchor}`,environment:'Keep the space and any item you need ready and visible.',reward:'Notice the calm or meaning of completing the small version.',ifThen:`After I ${anchor}, I will go to my chosen place and begin for two minutes.`,rationale:'A prepared space and an existing routine can make a reflective practice easier to begin.',focus:'Make the meaningful practice easy to begin',recommendations:['Prepare the space before the cue happens.','Use one stable anchor, such as after a meal or before bed.','Count the smallest sincere version as success.']}
  if (/journal|diary|gratitude|plan|reflect/.test(n)) return {minimum:'Write one sentence',cue:`After I ${anchor}`,environment:'Leave the notebook open with a pen where the cue happens.',reward:'Close the notebook after one honest sentence.',ifThen:`After I ${anchor}, I will write one sentence.`,rationale:'Reducing writing to a visible first sentence makes reflection less dependent on motivation.',focus:'Remove the blank-page barrier',recommendations:['Leave the notebook open to the next page.','Use the same prompt each day for one week.','Stop after one sentence if that is all you have.']}
  if (/brush|floss|teeth|skin|shower|hygiene/.test(n)) return {minimum:'Put the needed item in your hand',cue:`After I ${anchor}`,environment:'Place the item beside the routine you already do.',reward:'Check it off immediately after the smallest step.',ifThen:`After I ${anchor}, I will pick up the item and do the smallest version.`,rationale:'Placing the item at the existing routine removes remembering and setup from the action.',focus:'Attach the habit to an existing routine',recommendations:['Keep the item visible beside its anchor routine.','Reduce the setup to one movement.','Use a specific cue rather than a vague time of day.']}
  const action=first(name,'do the smallest useful action')
  return {minimum:`Start ${action} for two minutes`,cue:`After I ${anchor}`,environment:'Put the first item you need in plain sight before the cue.',reward:'Check it off as soon as the tiny version is complete.',ifThen:`After I ${anchor}, I will start ${action} for two minutes.`,rationale:'A specific cue, small action, and prepared environment support repetition without requiring perfect motivation.',focus:'Turn a broad intention into a visible first step',recommendations:['Name the first physical action, not the whole goal.','Prepare the first item before the cue happens.','Keep the minimum small enough for a difficult day.']}
}
